// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Places$ReactTemplate = require("./Places.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Places$ReactTemplate.make(/* array */[])), "places");

/*  Not a pure module */
