// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Utils$ReactTemplate = require("./Utils.bs.js");

var list = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.alignItems(Css.center),
          /* [] */0
        ]
      ]
    ]);

var contentWidth = Css.pct(50.0);

function place(backgroundUrl) {
  return Css.style(/* :: */[
              Css.display(Css.flexBox),
              /* :: */[
                Css.fontFamily("arial"),
                /* :: */[
                  Css.flexDirection(Css.column),
                  /* :: */[
                    Css.alignItems(Css.center),
                    /* :: */[
                      Css.textAlign(Css.center),
                      /* :: */[
                        Css.width(contentWidth),
                        /* :: */[
                          Css.height(Css.px(400)),
                          /* :: */[
                            Css.position(Css.relative),
                            /* :: */[
                              Css.marginTop(Css.px(50)),
                              /* :: */[
                                Css.marginBottom(Css.px(50)),
                                /* :: */[
                                  Css.justifyContent(Css.center),
                                  /* :: */[
                                    Css.before(/* :: */[
                                          Css.backgroundImage(Css.url(backgroundUrl)),
                                          /* :: */[
                                            Css.contentRule(""),
                                            /* :: */[
                                              Css.height(Css.pct(100.0)),
                                              /* :: */[
                                                Css.position(Css.absolute),
                                                /* :: */[
                                                  Css.opacity(0.3),
                                                  /* :: */[
                                                    Css.width(Css.pct(100.0)),
                                                    /* :: */[
                                                      Css.backgroundRepeat(Css.noRepeat),
                                                      /* :: */[
                                                        Css.backgroundSize(Css.cover),
                                                        /* :: */[
                                                          Css.backgroundPosition(Css.px(0), Css.px(0)),
                                                          /* [] */0
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]),
                                    /* :: */[
                                      Css.selector("&:hover > h2", /* :: */[
                                            Css.display(Css.none),
                                            /* [] */0
                                          ]),
                                      /* :: */[
                                        Css.selector("&:hover > div#description", /* :: */[
                                              Css.display(Css.flexBox),
                                              /* [] */0
                                            ]),
                                        /* :: */[
                                          Css.selector("&:hover > a > button", /* :: */[
                                                Css.display(Css.flexBox),
                                                /* :: */[
                                                  Css.visibility(Css.visible),
                                                  /* :: */[
                                                    Css.backgroundColor(Css.black),
                                                    /* :: */[
                                                      Css.color(Css.white),
                                                      /* :: */[
                                                        Css.paddingTop(Css.px(15)),
                                                        /* :: */[
                                                          Css.paddingBottom(Css.px(15)),
                                                          /* :: */[
                                                            Css.paddingRight(Css.px(32)),
                                                            /* :: */[
                                                              Css.paddingLeft(Css.px(32)),
                                                              /* :: */[
                                                                Css.textAlign(Css.center),
                                                                /* :: */[
                                                                  Css.textDecoration(Css.none),
                                                                  /* :: */[
                                                                    Css.display(Css.inlineBlock),
                                                                    /* :: */[
                                                                      Css.fontSize(Css.px(16)),
                                                                      /* :: */[
                                                                        Css.borderRadius(Css.px(10)),
                                                                        /* :: */[
                                                                          Css.opacity(0.8),
                                                                          /* :: */[
                                                                            Css.zIndex(2),
                                                                            /* [] */0
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]),
                                          /* [] */0
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var search = Css.style(/* :: */[
      Css.width(contentWidth),
      /* :: */[
        Css.height(Css.px(30)),
        /* :: */[
          Css.display(Css.flexBox),
          /* :: */[
            Css.flexDirection(Css.row),
            /* :: */[
              Css.marginTop(Css.px(40)),
              /* :: */[
                Css.fontSize(Css.px(20)),
                /* :: */[
                  Css.fontFamily("arial"),
                  /* :: */[
                    Css.opacity(0.5),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var placeName = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.width(Css.pct(100.0)),
        /* :: */[
          Css.opacity(0.8),
          /* :: */[
            Css.fontSize(Css.px(75)),
            /* :: */[
              Css.justifyContent(Css.center),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var placeDescription = Css.style(/* :: */[
      Css.display(Css.none),
      /* :: */[
        Css.flexDirection(Css.row),
        /* :: */[
          Css.fontFamily("arial"),
          /* :: */[
            Css.fontWeight(600),
            /* :: */[
              Css.fontSize(Css.px(35)),
              /* :: */[
                Css.opacity(1.0),
                /* :: */[
                  Css.paddingRight(Css.px(10)),
                  /* :: */[
                    Css.paddingLeft(Css.px(10)),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var button = Css.style(/* :: */[
      Css.display(Css.none),
      /* :: */[
        Css.visibility(Css.hidden),
        /* [] */0
      ]
    ]);

var Styles = /* module */[
  /* list */list,
  /* contentWidth */contentWidth,
  /* place */place,
  /* search */search,
  /* placeName */placeName,
  /* placeDescription */placeDescription,
  /* button */button
];

var component = ReasonReact.reducerComponent("NamesFromScratch");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: list
                        }, React.createElement("input", {
                              className: search,
                              placeholder: "Search",
                              onChange: (function ($$event) {
                                  return Curry._1(_self[/* send */3], /* Search */[$$event.target.value]);
                                })
                            }), Belt_Array.map(Utils$ReactTemplate.findPlace(_self[/* state */1][/* searchTerm */0]), (function (place$1) {
                                return React.createElement("div", {
                                            key: place$1[/* id */0],
                                            className: place(place$1[/* image */5][/* url */0])
                                          }, React.createElement("h2", {
                                                className: placeName
                                              }, Utils$ReactTemplate.s(place$1[/* name */1])), React.createElement("div", {
                                                className: placeDescription,
                                                id: "description"
                                              }, Utils$ReactTemplate.s(place$1[/* description */2])), React.createElement("a", {
                                                href: place$1[/* href */8],
                                                target: "_blank"
                                              }, React.createElement("button", {
                                                    className: button
                                                  }, Utils$ReactTemplate.s("Read about the "), Utils$ReactTemplate.s(place$1[/* name */1]))));
                              })));
            }),
          /* initialState */(function (param) {
              return /* record */[/* searchTerm */""];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              return /* Update */Block.__(0, [/* record */[/* searchTerm */action[0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Styles = Styles;
exports.component = component;
exports.make = make;
/* list Not a pure module */
